/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xmlproject;

import GUI.frmClient;
import java.io.BufferedWriter;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.nio.file.Files;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.transform.TransformerException;
import org.w3c.dom.Document;
import person.Person;
import static xmlproject.XMLProjectServer.calculateIBM;
import static xmlproject.XMLProjectServer.convertStringToDocument;
import static xmlproject.XMLProjectServer.createXML;
import static xmlproject.XMLReaderDOM.getList;

/**
 *
 * @author Brenda Bojorquez
 */
public class Client extends javax.swing.JFrame {

    DatagramSocket udpSocket;
            
            // Creates a ByteArrayOutputStream with default size
            ByteArrayOutputStream out;
            
            
            File myFile ;
            
            byte buffer[] ;
            
            DatagramPacket packet;
    
    public Client() {
        try {
            initComponents();
            udpSocket = new DatagramSocket();
            out = new ByteArrayOutputStream();
        } catch (SocketException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDoc = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        btnGet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDoc.setColumns(20);
        txtDoc.setRows(5);
        jScrollPane1.setViewportView(txtDoc);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnGet.setText("Get");
        btnGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSend)
                    .addComponent(btnGet))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnSend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        try {
            String name=JOptionPane.showInputDialog(null, "Enter file name: ");
            
            myFile = createDoc(name, txtDoc.getText());
            
            out.write(Files.readAllBytes(myFile.toPath()));
            
            buffer = out.toByteArray();
            
            packet = new DatagramPacket(buffer, buffer.length, InetAddress.getLocalHost(), 1001);
            
            udpSocket.send(packet);
            JOptionPane.showMessageDialog(null,"File Send");
            
            txtDoc.setText("");
            
        } catch (SocketException ex) {
            Logger.getLogger(frmClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(frmClient.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetActionPerformed
        try {
            // Check that the package is received
            buffer = new byte[1024];
            packet = new DatagramPacket(buffer, buffer.length);
            
            udpSocket.receive(packet);
            
            buffer = packet.getData();
            byte[] aux = new String(buffer).trim().getBytes();
            
            ByteArrayInputStream myStream = new ByteArrayInputStream(aux);
            
            //Method to get the String out of the bytes
            int size = myStream.available();
            char[] theChars = new char[size];
            byte[] bytes    = new byte[size];
            
            myStream.read(bytes, 0, size);
            for (int i = 0; i < size;)
                theChars[i] = (char)(bytes[i++]&0xff);
            
            //Save the chars in a String
            String data = new String(theChars);
            
            //Convert the String to an XML document
            Document doc = convertStringToDocument(data);
            
            //Path where the file is saved
            String filePath = "..\\XMLProject\\src\\files\\ClientReceived.xml";
            
            //Save the file
            createXML(doc, filePath);
            
            //Gets the list of people from the XML file
            List<Person> people = getList(filePath);
            
            //The list of people is calculated
            
            for (Person person : people) {
                calculateIBM(person);
                
                if (txtDoc.getText().isEmpty()) {
                    txtDoc.setText(person.getName()
                            + "\n" + person.getHeight()
                            + "\n" + person.getWeight()
                            + "\n" + person.getBmi()
                            + "\n" + person.getMeaning()+ "\n" );
                }
                else{
                    txtDoc.setText(txtDoc.getText()
                            + "\n" + person.getName()
                            + "\n" + person.getHeight()
                            + "\n" + person.getWeight()
                            + "\n" + person.getBmi()
                            + "\n" + person.getMeaning()+ "\n" );
                }
                
                System.out.println(person.getName());
                System.out.println(person.getHeight());
                System.out.println(person.getWeight());
                System.out.println(person.getBmi());
                System.out.println(person.getMeaning());
                System.out.println("");}
        } catch (TransformerException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }
    
    private File createDoc(String name, String content){
        
        
            String path = "..\\XMLProject\\src\\files\\"+name+".xml";
            File file = new File(path);
        try {
            // Si el archivo no existe es creado
            if (!file.exists()) {
                file.createNewFile();
            }
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(content);
            bw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return file;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGet;
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDoc;
    // End of variables declaration//GEN-END:variables
}
